@api = http://localhost:3000/tasks


### Get all tasks
{{api}}

### create a new task
POST {{api}}
Content-Type: application/json

{
  "title": "my third task",
  "description": "some third task"
}

### get a single task
{{api}}/5

### delete a single user
DELETE {{api}}/2

### get count
{{api}}/count

### update task
PUT {{api}}/5
Content-Type: application/json

{
  "title": "somperro",
  "description": "some new description 5 edit"
}